// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonBase: typeof import('./src/components/ButtonBase.vue')['default']
    CreateWishlistTile: typeof import('./src/components/CreateWishlistTile.vue')['default']
    FormWishlist: typeof import('./src/components/FormWishlist.vue')['default']
    FormWishlistItem: typeof import('./src/components/FormWishlistItem.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCart: typeof import('./src/components/icons/IconCart.vue')['default']
    IconCloudQuestion: typeof import('./src/components/icons/IconCloudQuestion.vue')['default']
    IconCreation: typeof import('./src/components/icons/IconCreation.vue')['default']
    IconDelete: typeof import('./src/components/icons/IconDelete.vue')['default']
    IconError: typeof import('./src/components/icons/IconError.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconImagePlaceholder: typeof import('./src/components/icons/IconImagePlaceholder.vue')['default']
    IconLightDark: typeof import('./src/components/icons/IconLightDark.vue')['default']
    IconLink: typeof import('./src/components/icons/IconLink.vue')['default']
    IconLogin: typeof import('./src/components/icons/IconLogin.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    IconNoGift: typeof import('./src/components/icons/IconNoGift.vue')['default']
    IconPencil: typeof import('./src/components/icons/IconPencil.vue')['default']
    IconSave: typeof import('./src/components/icons/IconSave.vue')['default']
    IconSpinner: typeof import('./src/components/icons/IconSpinner.vue')['default']
    IconToggleOff: typeof import('./src/components/icons/IconToggleOff.vue')['default']
    IconToggleOn: typeof import('./src/components/icons/IconToggleOn.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    ImageTile: typeof import('./src/components/ImageTile.vue')['default']
    'ImageTile copy': typeof import('./src/components/ImageTile copy.vue')['default']
    ImageTilePlaceholder: typeof import('./src/components/ImageTilePlaceholder.vue')['default']
    InputFile: typeof import('./src/components/InputFile.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    InputTextArea: typeof import('./src/components/InputTextArea.vue')['default']
    InputToggle: typeof import('./src/components/InputToggle.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    WishlistItem: typeof import('./src/components/WishlistItem.vue')['default']
  }
}

export {}
