name: 'CI'

on:
  push:
    branches: [main]
    tags-ignore: ['*']
  pull_request:
    branches: [main]

jobs:
  call-shared-ci:
    if: "!startsWith(github.event.head_commit.message, 'chore: bump version')"
    uses: ./.github/workflows/shared.yml
    with:
      run_docker: true
      run_docker_publish: false
      version: ${{ github.sha }}
