name: 'CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-shared-ci:
    uses: ./.github/workflows/shared.yml
    with:
      run_docker: true
      run_docker_publish: false
      version: ${{ github.sha }}
