name: 'Release'

on:
  release:
    types: [published]

jobs:
  call-shared-ci:
    uses: ./.github/workflows/shared.yml
    with:
      run_docker_test: true
      run_docker_publish: true
      version: ${{ github.event.release.tag_name # v1.0.0 }}
    secrets: inherit
